### ISSUE TITLE
migrate failing

### ISSUE THREAD

**Issue by Epaphus** [dotwaffle/pinder#2]
I am trying to set this up and when I run the migrate, I run into the following error.

```
$ ./manage.py migrate
System check identified some issues:

WARNINGS:
?: (1_7.W001) MIDDLEWARE_CLASSES is not set.
	HINT: Django 1.7 changed the global defaults for the MIDDLEWARE_CLASSES. django.contrib.sessions.middleware.SessionMiddleware, django.contrib.auth.middleware.AuthenticationMiddleware, and django.contrib.messages.middleware.MessageMiddleware were removed from the defaults. If your project needs these middleware then you should configure this setting.
Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 321, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/usr/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 291, in _reraise_missing_dependency
    raise exc
django.db.migrations.graph.NodeNotFoundError: Migration users.0001_initial dependencies reference nonexistent parent node (u'auth', u'0008_alter_user_username_max_length')

```

Running on Linux Mint 18 (Ubuntu 16.04) and Python 2.7.12

Any ideas on what might be causing the issue and how to fix it?

**Comment by dbarrosop** [comment]
Hi,
I think Django did some changes that weren't compabtible. Try installing the following dependencies:

```
ansible==2.1.2.0
cffi==1.8.3
cryptography==1.5.2
Django==1.10.2
django-crispy-forms==1.6.1
django-extensions==1.7.4
django-filter==0.15.3
djangorestframework==3.5.1
enum34==1.1.6
gtextfsm==0.2.1
hammock==0.2.4
idna==2.1
invoke==0.13.0
ipaddress==1.0.17
Jinja2==2.8
MarkupSafe==0.23
napalm-base==0.17.0
napalm-eos==0.3.0
netaddr==0.7.18
paramiko==2.0.2
pyasn1==0.1.9
pycparser==2.16
pycrypto==2.6.1
pyeapi==0.7.0
Pygments==2.1.3
PyYAML==3.12
requests==2.11.1
six==1.10.0
```

With those it works fine to me. Let's see if that fixes the issue in which case I guess we will have to make the code compatible with the latest django release.

Thx!

**Comment by Epaphus** [comment]
That worked.

Thanks.
